%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-sot-dynamic-pinocchio
Version:        3.6.3
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS sot-dynamic-pinocchio package

License:        BSD
URL:            http://stack-of-tasks.github.io
Source0:        %{name}-%{version}.tar.gz

Requires:       lapack-devel
Requires:       openblas-devel
Requires:       ros-noetic-catkin
Requires:       ros-noetic-dynamic-graph-python
Requires:       ros-noetic-pinocchio
Requires:       ros-noetic-sot-core
Requires:       ros-noetic-sot-tools
BuildRequires:  cmake
BuildRequires:  doxygen
BuildRequires:  git
BuildRequires:  gtest-devel
BuildRequires:  lapack-devel
BuildRequires:  openblas-devel
BuildRequires:  ros-noetic-dynamic-graph-python
BuildRequires:  ros-noetic-pinocchio
BuildRequires:  ros-noetic-sot-core
BuildRequires:  ros-noetic-sot-tools
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Pinocchio bindings for dynamic-graph

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/noetic

%changelog
* Fri Mar 12 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 3.6.3-1
- Autogenerated by Bloom

* Fri Mar 12 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 3.6.2-3
- Autogenerated by Bloom

* Fri Mar 12 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 3.6.2-2
- Autogenerated by Bloom

* Fri Mar 12 2021 Guilhem Saurel <guilhem.saurel@laas.fr> - 3.6.2-1
- Autogenerated by Bloom

